# This the the default config. Copy to a user directory to customize.

# BinMode simply lists the contents of PATH
[modes.binary]
class = "searchtool_gtk.modes.BinMode"

# FileMode lists files according to wcmatch-style glob patterns.
[modes.file]
class = "searchtool_gtk.modes.FileMode"
patterns = [
  # "~/Documents/*.pdf",
]

# All other values are optional.
# For example, if you can have more than one file mode active, you may want to customize the title
title = "Books"

# You can optionally customize the wcmatch flags.
wcmatch_flags = ["NEGATE", "GLOBSTAR", "BRACE", "GLOBTILDE"]

# ICU collation options for the file mode
# icu_locale =
# icu_strength =

# ClipHistMode is useful for, well, cliphist
[modes.clipboard]
class = "searchtool_gtk.modes.ClipHistMode"

# ICU collation options for the ClipHist mode
# icu_locale =
# icu_strength =
