# This the the default config

[modes.binary]
class = "searchtool_gtk.modes.BinMode"
# stdout =  # Override the subprocess stream modes; can be "INHERIT" or "DEVNULL"
# stderr =  # Ditto

# # The FileMode is commented out by default because it has a mandatory "patterns" config which cannot be set universally
# [modes.file]
# class = "searchtool_gtk.modes.FileMode"
# patterns = [
#   "~/Documents/*.pdf",
# ]
# wcmatch_flags = ["NEGATE", "GLOBSTAR", "BRACE", "GLOBTILDE"]  # The default wcmatch flags we use
# icu_locale =  # Optional ICU locale
# icu_strength =  # Optional strength of matching strings; lower is looser

# # The ClipHistMode accepts no options and "just works" if enabled
# [modes.clipboard]
# class = "searchtool_gtk.modes.ClipHistMode"
