# This the the default config

[[modes]]
name = "Binary"
class = "searchtool_gtk.modes.BinMode"

# # Optional config
# [modes.param]
# stdout =  # Subprocess stream modes; can be "INHERIT" or "DEVNULL"
# stderr =  # Ditto

# # The File mode has a mandatory "glob" config (see below), so it is optional
# [[modes]]
# name = "File"
# class = "searchtool_gtk.modes.FileMode"

# [modes.param]
# patterns = [
#   "~/Documents/*.pdf",
#   # For legacy stdlib glob matching, you can set the `include_hidden` and `recursive` options
#   { glob = "~/Documents/*.pdf", include_hidden = true, recursive = true },
# ]
# use_wcmatch = true  # Use wcmatch for glob matching
# wcmatch_flags = ["NEGATE", "GLOBSTAR", "BRACE", "GLOBTILDE"]  # The default wcmatch flags we use
# icu_locale =  # Optional ICU locale
# icu_strength =  # Optional strength of matching strings; lower is looser

# # The ClipHist mode is also commented out by default, but can easily be re-enabled
# [[modes]]
# name = "ClipHist"
# class = "searchtool_gtk.modes.ClipHist"
